name: integration tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  integration-tests:
    name: Integration Tests (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        dart-version: ['stable']
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Set up Dart SDK ${{ matrix.dart-version }}
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart-version }}

      - name: Run Integration Tests
        run: ./gradlew :test --tests "com.jetbrains.dart.*"
        working-directory: third_party

      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: integration-test-results
          path: |
            **/build/reports/
            **/build/test-results/
